### ISSUE TITLE
Naming issues re: go src/repo name

### ISSUE THREAD

**Issue by asachs01** [ncr-devops-platform/nagiosfoundation#164]
I'm not so sure if this is a big deal or not, but many of the checks refer to the path of the library as `ncr-devops-platform/nagiosfoundation`, when performing a `go get` or `git clone` yields a path of `/nagios-foundation`. This leads to VS code griping quite a bit. Simply doing a `mv` solves the issue, but being able to download the repo w/out the the potential for VS code (or any other editor, for that matter) to gripe would be 👍

**Comment by quaggoth** [comment]
Agreed here. This repo should be renamed to remove the `-`. This has caused me headaches a few times. However, this should be done with a plan in mind. Most importantly, a repo rename will break the Travis build and less importantly, our build documentation. It should be done one morning when I have the day to clean up after this change.

The [BUILDING](https://github.com/ncr-devops-platform/nagios-foundation/blob/master/BUILDING.md) documentation has a blurb about using a target directory for the `git checkout` command because of this:

```
git clone https://github.com/ncr-devops-platform/nagios-foundation.git nagiosfoundation
```

The Travis build also had to account for this in the install section:

```
- mv /home/travis/gopath/src/github.com/ncr-devops-platform/nagios-foundation /home/travis/gopath/src/github.com/ncr-devops-platform/nagiosfoundation
```

**Comment by quaggoth** [comment]
Repository has been renamed. Closing.
