### ISSUE TITLE
check_performance_counter needs additional examples

### ISSUE THREAD

**Issue by ohhfine** [ncr-devops-platform/nagiosfoundation#188]
while (and please forgive me i am noob) it may just be me and new exposure to sensu go i'm having an issue with this command that may be related to delimiting the backslash in the performance counter name, generally just spewing errors, im sure there is opportunity to update the readme to aid others, its a very promising and valuable command

skipper@backend:~$ cat << EOF | sensuctl create
> {
>   "type": "CheckConfig",
>   "api_version": "core/v2",
>   "metadata": {
>     "name": "windows-check-cpu",
>     "namespace": "default"
>   },
>   "spec": {
>     "command": "check_performance_counter -n "\Processor Information(*)\% Processor Time"",
>     "interval": 250,
>     "publish": true,
>     "runtime_assets": [
>       "nagiosfoundation-0.1.0"
>     ],
>     "subscriptions": [
>       "windows"
>     ]
>   }
> }
> EOF
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
resource 0: invalid character 'P' in string escape code
Error: in stdin: too many errors
skipper@backend:~$

skipper@backend:~$ uname -a
Linux backend 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
skipper@backend:~$

**Comment by ohhfine** [comment]
updated error message ignore the first one

skipper@backend:~$ cat << EOF | sensuctl create
> {
>   "type": "CheckConfig",
>   "api_version": "core/v2",
>   "metadata": {
>     "name": "windows-check-cpu",
>     "namespace": "default"
>   },
>   "spec": {
>     "command": "check_performance_counter -n "\Processor Information(*)\% Processor Time"",
>     "interval": 250,
>     "publish": true,
>     "runtime_assets": [
>       "nagiosfoundation-0.1.0"
>     ],
>     "subscriptions": [
>       "windows"
>     ]
>   }
> }
> EOF
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
resource 0: invalid character '\\' after object key:value pair
Error: in stdin: too many errors
skipper@backend:~$

**Comment by ohhfine** [comment]
trial and error, i kept trying, eventually have it running as designed, i assume

**Comment by quaggoth** [comment]
Your problem has nothing to do with `check_performance_counter` or `sensuctl` and everything to do with the [CLI shell](https://en.wikipedia.org/wiki/Shell_(computing)#Command-line_shells) you're using. Additionally, every shell has a different CLI implementation whether it be the [Bourne shell](https://en.wikipedia.org/wiki/Bourne_shell) (`sh`), the [Bourne Again shell](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) (`bash`), or the [friendly interactive shell](https://fishshell.com/) (`fish`) which are typically found on Linuxy systems. On Windows you have [`cmd.exe`](https://en.wikipedia.org/wiki/Cmd.exe) and [PowerShell](https://docs.microsoft.com/en-us/powershell/) (`powershell.exe`). To further complicate matters, some of these shells are cross-platform. Install [Git for Windows](https://gitforwindows.org/) and you could be running these commands under bash, or maybe you've installed PowerShell on your Linux machine and are using that. All these shells use different escape characters and that character can even change in the shell depending on where and how you're using it. The back-slash (`\`) _usually_ figures into escape character usage, which is why you're running into problems when you issue a command line like yours _from the command line interface_. Not knowing the operating system and shell you are using makes resolving your issue nearly impossible (though admittedly, from your prompt, it looks as if you may be using bash under Linux).

When you run into a situation like this, looking for alternative means can be a better solution. In this case, feeding `sensuctl` the data using a file rather than using [`stdin`](https://en.wikipedia.org/wiki/Standard_streams) will take the command line interface out of the equation, giving you just `sensuctl` to deal with. Taking at look at the [documentation for `sensuctl`](https://docs.sensu.io/sensu-go/latest/sensuctl/create-manage-resources/) we can see it has a `--file` option.

My suggestion is to save your data to a file (all the lines between `cat << EOF | sensuctl create` and `EOF`) named something like `perfcheck.txt`, then using the `--file` option, issue a command such as `sensuctl create --file perfcheck.txt` and see if that helps out. Once your begin approaching your problem this way, it'll make for easier troubleshooting since you've taken the CLI, file redirection, and escape characters out of the equation.

Once again, your problem doesn't have anything to do with the `check_performance_counter` check and instead is with the the command line interface you're using, which is probably part of why there's been little feedback here. Giving full examples that use stdin and pipes using all the different shells and operating systems would be quite an undertaking and I would say is out of the domain of this project.

Hope this background information and these suggestions help.

**Comment by ohhfine** [comment]
Thank you for your response, that is exactly what I have done as I have gained a bit more exposure to sensu go, the file method is much easier , as well i find using the yaml format makes it look much more readable(just a personal opinion)  looking forward to learning more as time goes on

Andrew



________________________________
